name: Pull Request

on:
  pull_request:
    branches:
      - master
  workflow_dispatch:


jobs:
  bundle-ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install dependencies
        run: yarn install
      - name: Bundle
        run: npx nx bundle-ios ${{ (github.repository.split("/")).at(1)}}
      - name: Upload bundle
        uses: actions/upload-artifact@v3
        with:
          name: ios-bundle
          path: ./dist/apps/${{ (github.repository.split("/")).at(1)}}/ios/main.jsbundle

  test:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 16
    - name: Install dependencies
      run: yarn install
    - name: Run Unit Tests
      run: npx nx test ${{ (github.repository.split("/")).at(1)}}

  lint:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 16
    - name: Install dependencies
      run: yarn install
    - name: Lint
      run: npx nx lint ${{ (github.repository.split("/")).at(1)}}


