name: Pull Request

on:
  pull_request:
    branches:
      - master
  workflow_dispatch:


jobs:
  bundle-ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v3.6.0
        with:
          node-version: 16
          cache: yarn
      - name: Install dependencies
        run: yarn install
      - name: Get Repository Name
        uses: actions/github-script@v6.4.0
        id: repository-data
        with:
          script: |
            const name: String = github.repository
              const repoName = name.split('/').at(1)
            core.setOutput('repo-name', repoName)
      - name: Bundle
        run: npx nx bundle-ios ${{ steps.repository-data.outputs.repo-name}}
      - name: Upload bundle
        uses: actions/upload-artifact@v3
        with:
          name: ios-bundle
          path: ./dist/apps/${{ steps.repository-data.outputs.repo-name}}/ios/main.jsbundle

  test:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v3.6.0
      with:
        node-version: 16
        cache: yarn
    - name: Install dependencies
      run: yarn install
    - name: Get Repository Name
      uses: actions/github-script@v6.4.0
      id: repository-data
      with:
        script: |
            const name: String = github.repository
            const repoName = name.split('/').at(1)
            core.setOutput('repo-name', repoName)
    - name: Run Unit Tests
      run: npx nx test ${{ steps.repository-data.outputs.repo-name}}

  lint:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v3.6.0
      with:
        node-version: 16
        cache: yarn
    - name: Install dependencies
      run: yarn install
    - name: Get Repository Name
      uses: actions/github-script@v6.4.0
      id: repository-data
      with:
        script: |
          const name: String = github.repository
          const repoName = name.split('/').at(1)
          core.setOutput('repo-name', repoName)
    - name: Lint
      run: npx nx lint ${{ steps.repository-data.outputs.repo-name}}


